"""Adapter that exposes the legacy PiLiDAR LiDAR interface on top of the SDK driver."""

from __future__ import annotations

import time
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

from lib.pointcloud import get_scan_dict, save_raw_scan

from .driver import STL27LDriver


class STL27LAdapter:
    """Bridge the new SDK based driver to the interface expected by ``ScanController``.

    The adapter collects the full LiDAR data stream – including timestamped
    packages, cartesian point lists and the platform angle – so that the raw
    pickle files match the historic structure generated by ``lib.lidar_driver``.
    A stepper log can optionally be attached by the controller and will be
    embedded in the raw scan dictionary.
    """

    def __init__(self, config, port: str = "/dev/ttyUSB0", baud: int = 921600) -> None:
        self.cfg = config
        self.port = port
        self.baud = baud
        self.driver = STL27LDriver(port=port, baud=baud)

        self._status_cb: Optional[Callable[[str], None]] = None
        self._stop = False
        self.z_angle: float = 0.0

        # Configuration values reused from the legacy driver
        device = getattr(self.cfg, "DEVICE", None) or self.cfg.get("LIDAR", "DEVICE")
        offset_deg = self.cfg.get("LIDAR", device, "OFFSET", default=0.0)
        self._offset_rad = np.deg2rad(offset_deg)
        # Motor control is now handled by driver constants

        # Collected data buffers reset for every read_loop invocation
        self.package_history: List[Dict[str, Any]] = []
        self.angular_list: List[np.ndarray] = []
        self.cartesian_list: List[np.ndarray] = []
        self.z_angles: List[Optional[float]] = []
        self.stepper_log: List[Dict[str, float]] = []

        # File destinations are prepared by ``Config.init``
        self.raw_path = getattr(self.cfg, "raw_path", None)

    # ------------------------------------------------------------------
    # Controller facing API
    # ------------------------------------------------------------------
    def set_status_callback(self, cb: Callable[[str], None]) -> None:
        self._status_cb = cb

    def power_on(self) -> None:
        if self._status_cb:
            self._status_cb("LiDAR: power_on()")

    def start_motor(self) -> None:
        self.driver.start()
        ok = self.driver.wait_connect(2000)
        if self._status_cb:
            self._status_cb(f"LiDAR: wait_connect -> {ok}")
        if not ok:
            raise RuntimeError("LiDAR nicht erreichbar (keine Pakete)")

        try:
            self.driver.motor_start()
            if self._status_cb:
                self._status_cb("LiDAR: Motorstart-Befehl gesendet.")
        except Exception as exc:  # pragma: no cover - serial availability
            if self._status_cb:
                self._status_cb(f"LiDAR: Motorstart-Befehl fehlgeschlagen ({exc}).")

    def stop_motor(self) -> None:
        # Send UART motor stop command
        try:
            self.driver.motor_stop()
            if self._status_cb:
                self._status_cb("LiDAR: Motorstop-Befehl gesendet.")
        except Exception as exc:  # pragma: no cover - serial availability
            if self._status_cb:
                self._status_cb(f"LiDAR: Motorstop-Befehl fehlgeschlagen ({exc}).")
        
        # Set GPIO pin 17 to HIGH to disable stepper motor
        self._force_pin17_high()
        
        self.driver.stop()
        if self._status_cb:
            self._status_cb("LiDAR: stop_motor()")

    def request_stop(self) -> None:
        self._stop = True

    def read_loop(
        self,
        callback: Optional[Callable[[], None]] = None,
        max_packages: Optional[int] = None,
    ) -> None:
        """Continuously read LiDAR packets until told to stop."""

        self._stop = False
        self._reset_buffers()
        count = 0
        last_status_ts = time.time()

        while not self._stop:
            if callback:
                callback()

            pkt = self.driver.get_scan(timeout_ms=200)
            if pkt is None:
                if time.time() - last_status_ts > 1.5 and self._status_cb:
                    self._status_cb("LiDAR: warte auf Paket...")
                    last_status_ts = time.time()
                continue

            packet_data = self._convert_packet(pkt)
            if packet_data is None:
                continue

            self._append_packet(packet_data)
            count += 1
            if max_packages is not None and count >= max_packages:
                break

        if self._status_cb:
            self._status_cb("LiDAR: read_loop beendet")

    def create_raw_scan(self, metadata: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Serialize the collected LiDAR data using the legacy pickle layout."""

        metadata = metadata or {}
        if "samples" not in metadata:
            metadata["samples"] = len(self.package_history)

        raw_scan = get_scan_dict(
            self.z_angles,
            angular_list=self.angular_list,
            cartesian_list=self.cartesian_list,
            packages=self.package_history,
            metadata=metadata,
            stepper_log=list(self.stepper_log),
        )

        if self.raw_path:
            save_raw_scan(self.raw_path, raw_scan)
        return raw_scan

    def close(self) -> None:
        # Stop motor and set pin 17 HIGH
        self.stop_motor()
        self.driver.stop()
        # Ensure pin 17 stays HIGH after close
        self._force_pin17_high()
        if self._status_cb:
            self._status_cb("LiDAR: close() - Motor gestoppt, Pin 17 auf HIGH")

    def _force_pin17_high(self) -> None:
        """Force GPIO pin 17 to HIGH state to ensure stepper motor stays disabled."""
        try:
            import os
            os.environ.setdefault("RPI_LGPIO_REVISION", "0xa020d3")
            import RPi.GPIO as GPIO
            GPIO.setwarnings(False)
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(17, GPIO.OUT)
            GPIO.output(17, GPIO.HIGH)
            if self._status_cb:
                self._status_cb("LiDAR: Pin 17 auf HIGH gesetzt (Stepper deaktiviert).")
        except Exception as exc:
            if self._status_cb:
                self._status_cb(f"LiDAR: Pin 17 konnte nicht gesetzt werden ({exc}).")

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _reset_buffers(self) -> None:
        self.package_history.clear()
        self.angular_list.clear()
        self.cartesian_list.clear()
        self.z_angles.clear()

    def _convert_packet(
        self, pkt: Sequence[Any]
    ) -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
        if not pkt:
            return None

        angles_deg = np.array([point.angle_deg for point in pkt], dtype=np.float32)
        distances_mm = np.array([point.distance_mm for point in pkt], dtype=np.float32)
        intensities = np.array([point.intensity for point in pkt], dtype=np.float32)
        timestamps_ns = np.array([point.stamp_ns for point in pkt], dtype=np.int64)

        angles_rad = np.deg2rad(angles_deg).astype(np.float32)
        cartesian = self._polar_to_cartesian(angles_rad, distances_mm, intensities)
        angular = np.column_stack((angles_rad, distances_mm, intensities)).astype(np.float32)
        return angles_rad, distances_mm, intensities, timestamps_ns, cartesian, angular

    def _polar_to_cartesian(
        self,
        angles_rad: np.ndarray,
        distances_mm: np.ndarray,
        intensities: np.ndarray,
    ) -> np.ndarray:
        """Convert polar LiDAR samples into cartesian coordinates.

        The legacy pipeline expects a 4-column layout ``[x, y, z, intensity]``
        where ``z`` is initially zero and later populated during the merging
        stage.  We therefore extend the planar LiDAR samples accordingly so
        downstream processing behaves exactly as before the SDK transition.
        """

        adjusted_angles = angles_rad + self._offset_rad
        distances = distances_mm.astype(np.float32)
        x_vals = -distances * np.cos(adjusted_angles)
        y_vals = distances * np.sin(adjusted_angles)
        zeros = np.zeros_like(x_vals)
        return np.column_stack((x_vals, y_vals, zeros, intensities)).astype(np.float32)

    def _append_packet(
        self,
        packet_data: Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray],
    ) -> None:
        angles_rad, distances_mm, intensities, timestamps_ns, cartesian, angular = packet_data

        # Robuste Geschwindigkeitsabfrage mit Fehlerbehandlung
        try:
            speed_deg_s = self.driver.get_spin_deg_per_s()
            if speed_deg_s <= 0 or speed_deg_s > 3600:  # Plausibilitätsprüfung
                speed_deg_s = 600.0  # Fallback für STL27L
        except Exception as exc:
            speed_deg_s = 600.0  # Sicherer Fallback
            if self._status_cb:
                self._status_cb(f"LiDAR: Geschwindigkeitsabfrage fehlgeschlagen, verwende Fallback ({exc})")
        
        timestamp_s = float(timestamps_ns[-1]) / 1e9

        packet_entry = {
            "timestamp": timestamp_s,
            "timestamps_ns": timestamps_ns.astype(np.int64, copy=True),
            "speed": speed_deg_s,
            "angles_rad": angles_rad.copy(),
            "distances_mm": distances_mm.copy(),
            "intensities": intensities.copy(),
            "cartesian": cartesian.copy(),
            "z_angle": float(self.z_angle) if self.z_angle is not None else None,
        }

        self.package_history.append(packet_entry)
        self.angular_list.append(angular.copy())
        self.cartesian_list.append(cartesian.copy())
        self.z_angles.append(float(self.z_angle) if self.z_angle is not None else None)
